### ISSUE TITLE
Re: Exposed Ports

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#1]
With your docker-compose file:
```
version: '3'
services:
  target_1:
    build: .
    command: node app.js target
    ports:
      - 9997:9997
  target_2:
    build: .
    command: node app.js target
    ports:
      - 9998:9997
  splitter:
    build: .
    command: node app.js splitter
    ports:
      - 9999:9997
    depends_on:
      - target_1
      - target_2
  agent:
    build: .
    command: node app.js agent
    ports:
      - 10000:9997
    depends_on:
      - splitter
```
I'm curious if there is a way to do this where we don't need to expose the ports externally?
