### ISSUE TITLE
Re: events.log

### ISSUE THREAD

**Issue by smilinazzo** [sloan111/NodeEcosystsm#2]
With your docker-compose file:
```
version: '3'
services:
  target_1:
    build: .
    command: node app.js target
    ports:
      - 9997:9997
  target_2:
    build: .
    command: node app.js target
    ports:
      - 9998:9997
  splitter:
    build: .
    command: node app.js splitter
    ports:
      - 9999:9997
    depends_on:
      - target_1
      - target_2
  agent:
    build: .
    command: node app.js agent
    ports:
      - 10000:9997
    depends_on:
      - splitter
```
How would you go about doing this so that you don't need to copy the events.log off of the container and go through the process of untaring, etc?
